### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZolarZ** [Altify-Development/Gmail-Generator-Python#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Gmail-Generator-Python-main\source\gmail_generator.py", line 188, in <module>
    if open_firefox() :
  File "C:\Users\Administrator\Desktop\Gmail-Generator-Python-main\source\gmail_generator.py", line 48, in open_firefox
    _location_=pyautogui.center(_start_button_)
  File "C:\Python310\lib\site-packages\pyscreeze\__init__.py", line 582, in center
    return Point(coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
TypeError: 'NoneType' object is not subscriptable

**Comment by Altify-Development** [comment]
have you installed the required pips?
